export const affirmations = [
    {quoteText: "Asking for help is a sign of self-respect and self-awareness."},
    {quoteText: "Changing my mind is a strength, not a weakness."},
    {quoteText: "Every decision I make is supported by my whole and inarguable experience."},
    {quoteText: "I affirm and encourage others, as I do myself."},
    {quoteText: "I alone hold the truth of who I am."},
    {quoteText: "I am allowed to ask for what I want and what I need."},
    {quoteText: "I am allowed to feel good."},
    {quoteText: "I am capable of balancing ease and effort in my life."},
    {quoteText: "I am complete as I am, others simply support me."},
    {quoteText: "I am content and free from pain."},
    {quoteText: "I am doing the work that works for me."},
    {quoteText: "I am good and getting better."},
    {quoteText: "I am growing and I am going at my own pace."},
    {quoteText: "I am held and supported by those who love me."},
    {quoteText: "I am in charge of how I feel and I choose to feel happy."},
    {quoteText: "I am listening and open to the messages the universe has to offer today."},
    {quoteText: "I am loved and worthy."},
    {quoteText: "I am more than my circumstances dictate."},
    {quoteText: "I am open to healing."},
    {quoteText: "I am optimistic because today is a new day."},
    {quoteText: "I am peaceful and whole."},
    {quoteText: "I am proof enough of who I am and what I deserve."},
    {quoteText: "I am responsible for myself, and I start there."},
    {quoteText: "I am safe and surrounded by love and support."},
    {quoteText: "I am still learning so it’s okay to make mistakes."},
    {quoteText: "I am understood and my perspective is important."},
    {quoteText: "I am valued and helpful."},
    {quoteText: "I am well-rested and excited for the day."},
    {quoteText: "I am worthy of investing in myself."},
    {quoteText: "I belong here, and I deserve to take up space."},
    {quoteText: "I breath in healing, I exhale the painful things that burden my heart."},
    {quoteText: "I breathe in trust, I exhale doubt."},
    {quoteText: "I can be soft in my heart and firm in my boundaries."},
    {quoteText: "I can control how I respond to things that are confronting."},
    {quoteText: "I can hold two opposing feelings at once, it means I am processing."},
    {quoteText: "I celebrate the good qualities in others and myself."},
    {quoteText: "I deserve an affirming touch on my own terms."},
    {quoteText: "I deserve information and I deserve moments of silence, too."},
    {quoteText: "I deserve self-respect and a clean space."},
    {quoteText: "I do all things in love."},
    {quoteText: "I do not have to linger in dark places; there is help for me here."},
    {quoteText: "I do not pretend to be anyone or anything other than who I am."},
    {quoteText: "I do not rise and fall for another."},
    {quoteText: "I do not rush through my life, I temper speed with stillness."},
    {quoteText: "I embrace change seamlessly and rise to the new opportunity it presents."},
    {quoteText: "I embrace the questions in my heart and welcome the answers in their own time."},
    {quoteText: "I grow towards my interests, like a plant reaching for the sun."},
    {quoteText: "I have come farther than I would have ever thought possible, and I’m learning along the way."},
    {quoteText: "I have everything I need to succeed."},
    {quoteText: "I hold community for others, and am held in community by others."},
    {quoteText: "I hold wisdom beyond knowledge."},
    {quoteText: "I invite abundance and a generous heart."},
    {quoteText: "I invite art and music into my life."},
    {quoteText: "I leave room in my life for spontaneity."},
    {quoteText: "I let go of the things that sit achingly out of reach."},
    {quoteText: "I look forward to tomorrow and the opportunities that await me."},
    {quoteText: "I love that I love what I love."},
    {quoteText: "I make decisions based on a good gut, I make changes based on a growing heart."},
    {quoteText: "I make time to experience grief and sadness when necessary."},
    {quoteText: "I nourish myself with kind words and joyful foods."},
    {quoteText: "I practice gratitude for all that I have, and all that is yet to come."},
    {quoteText: "I release the fears that do not serve me."},
    {quoteText: "I respect the cycle of the seasons."},
    {quoteText: "I seek out mystery in the ordinary."},
    {quoteText: "I strive for joy, not for perfection."},
    {quoteText: "I tell the truth about who I am and what I need from others."},
    {quoteText: "I uplift my joy and the joy of others."},
    {quoteText: "I welcome the wisdom that comes with growing older."},
    {quoteText: "I welcome what is, I welcome what comes."},
    {quoteText: "I will allow myself to evolve."},
    {quoteText: "Letting go creates space for opportunities to come."},
    {quoteText: "My body is beautiful in this moment and at its current size."},
    {quoteText: "My body is worthy of being cared for and adorned in beautiful garments."},
    {quoteText: "My feelings deserve names, deserve recognition, deserve to be felt."},
    {quoteText: "My heart is open to helpfulness from myself and from others."},
    {quoteText: "My heart knows its own way."},
    {quoteText: "My life is not a race or competition."},
    {quoteText: "My perspective is unique and important."},
    {quoteText: "My pleasure does not require someone else’s pain."},
    {quoteText: "My sensitivity is beautiful, and my feelings and emotions are valid."},
    {quoteText: "My weirdness is wonderful."},
    {quoteText: "Saying “no” is an act of self-affirmation, too."},
    {quoteText: "Sometimes the work is resting."},
    {quoteText: "There is growth in stillness."},
    {quoteText: "There is peace in changing your mind when it is done in love."},
    {quoteText: "There is poetry in everything, if I look for it."},
    {quoteText: "There is room for me at the table."},
    {quoteText: "There is something in this world that only I can do. That is why I am here."},
    {quoteText: "There is strength in quiet, there is vulnerability in being loud."},
    {quoteText: "Today I celebrate that I am younger than I’m ever going to be."},
    {quoteText: "Today is an opportunity to grow and learn."},
    {quoteText: "When I feel fear, I feed trust."},
    {quoteText: "When I focus on my reason for being, I am infinitely brave."},
    {quoteText: "When I forgive myself, I free myself."},
    {quoteText: "When I release shame, I move into myself more beautifully."},
    {quoteText: "When I root into the earth, the earth rises to support me."},
    {quoteText: "When I speak my needs, I receive them abundantly."},
    {quoteText: "When I talk to myself as I would a friend, I see all my best qualities and I allow myself to shine."},
    {quoteText: "Words may shape me, but they do not make me. I am here already."},
]
