import '@/styles/globals.css'
import styled from '@emotion/styled';
import { Home, Image as ImageIcon, EditNote } from '@mui/icons-material';
import { createTheme, Fab, ThemeProvider } from '@mui/material';
import type { AppProps } from 'next/app'
import Head from 'next/head';
import Link from 'next/link';
import { Provider } from 'react-redux';
import { wrapper } from '../store/store';

const Header = styled.div`
    position: absolute;
    z-index: 1;
    top: 5%;
    left: 4%;
`;
const theme = createTheme({
  palette: {
    primary: {
      main: "#00BCD4",
      light: "#4DD0E1",
      dark: "#0097A7",
      contrastText: "#FFFFFF"
    },
    secondary: {
      main: "#EC407A",
      light: "#EC407A",
      dark: "#AD1457",
      contrastText: "#FFFFFF"
    }
  },
});

export default function App({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;

  return (
    <ThemeProvider theme={theme}>
    <Provider store={store}>
      <main>
        <Head>
          <title>Mindful Moments</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/flower-1.svg" />
        </Head>
        <>
          <Header>
            <Fab size="medium" color="primary" style={{marginRight: 20}} aria-label="home">
              <Link href="/"><Home style={{marginTop: 3}} /></Link>
            </Fab>
            {/* <Fab size="medium" color="primary" style={{marginRight: 20}} aria-label="favorites">
              <Link href="/favorites"><ImageIcon style={{marginTop: 5}} /></Link>
            </Fab> */}
            <Fab size="medium" color="primary" aria-label="favorites">
              <Link href="/custom-quotes"><EditNote style={{marginTop: 7, marginLeft: 5}} /></Link>
            </Fab>
          </Header>
          <Component {...pageProps} />
        </>
      </main>
    </Provider>
    </ThemeProvider>
  );
}
