import Head from 'next/head'
import QuotePage from '@/components/QuotePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Quoted Journey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/flower-1.svg" />
      </Head>
      <main>
        <QuotePage />
      </main>
    </>
  )
}
